# Random number generation codes for normal distribution 

In [1]:
import numpy as np

In [2]:
np.random.randn(10)       # 標準正規分布を10個生成

array([-0.07593375, -1.80527356,  0.08964189,  0.34600399, -0.43356141,
        0.67402529,  0.39326608, -0.8382901 , -0.27580218,  1.02891147])

平均や分散を指定したい場合はnormalを使う

In [3]:
np.random.normal(50,10,size=100)   # 平均50、標準偏差10の正規分布で100個の乱数を生成

array([50.54843805, 41.90603575, 62.22386992, 50.40656422, 38.10014718,
       53.25031083, 70.73949088, 60.54254245, 50.5790209 , 29.65481942,
       57.6785083 , 51.1544986 , 42.66089145, 64.24807663, 43.70905733,
       46.08723468, 64.02044241, 50.6450843 , 51.74083453, 32.3438821 ,
       54.25829076, 56.71093566, 24.72751658, 36.30849335, 51.82043605,
       53.61792558, 54.55720051, 39.834752  , 54.42964228, 54.17790633,
       51.29693246, 42.99272504, 47.12875   , 31.45252185, 39.70105726,
       58.61594463, 64.9178752 , 42.52319771, 53.58534955, 33.48162686,
       52.12134806, 52.51579134, 46.15451389, 57.31909519, 45.89023174,
       24.66996488, 37.45964602, 46.89782018, 44.79932383, 55.01862168,
       52.00913204, 48.47935003, 68.52017015, 57.65796249, 59.75902246,
       51.29273581, 48.85196504, 50.6328579 , 43.30907254, 47.36371106,
       57.52373958, 52.85408764, 69.10572941, 50.89219222, 43.36992607,
       42.05002663, 50.92748554, 53.32213946, 48.1393659 , 42.21

# Random number generation codes for uniform distribution 

In [4]:
np.random.rand(100)   # 0〜1の乱数を100個生成

array([0.28462407, 0.46425698, 0.93253283, 0.73266723, 0.9658527 ,
       0.31894491, 0.638393  , 0.18331661, 0.30757717, 0.94745102,
       0.21011592, 0.67049041, 0.83405511, 0.04329486, 0.72041763,
       0.49841514, 0.40734707, 0.34069591, 0.65351168, 0.05711498,
       0.87980088, 0.92772087, 0.85291794, 0.01054701, 0.07773862,
       0.0610688 , 0.29894103, 0.07289953, 0.08026349, 0.23588572,
       0.64005904, 0.43899443, 0.78496529, 0.42700751, 0.32735293,
       0.1706371 , 0.03778376, 0.1483335 , 0.29410155, 0.98241885,
       0.2011637 , 0.64237512, 0.24294115, 0.47191636, 0.6782604 ,
       0.73930774, 0.772309  , 0.24194482, 0.10826157, 0.15326869,
       0.51921395, 0.64354461, 0.85490998, 0.17254109, 0.82210412,
       0.01552326, 0.02932207, 0.86421438, 0.77149138, 0.25177092,
       0.4014419 , 0.38920367, 0.02916272, 0.34332396, 0.4407818 ,
       0.07554055, 0.11287563, 0.01361673, 0.04555019, 0.09708537,
       0.99652532, 0.89913936, 0.46369857, 0.84350659, 0.67724

#  shuffling and permutation

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.random.shuffle(arr) #並べ替える
arr

array([7, 6, 0, 8, 2, 4, 3, 9, 1, 5])

In [7]:
arr2 = np.arange(9).reshape((3, 3)) #1次元配列を3*3の二次元配列に変換
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.random.shuffle(arr2) #多次元の場合は最初のaxisに沿ってシャッフルされる
arr2

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [9]:
np.random.permutation(10) #permutationもshuffleと同じだがコピーが作成される点と配列だけでなくint型整数も渡せる点が異なる

array([4, 5, 1, 7, 6, 0, 9, 3, 8, 2])

In [10]:
np.random.permutation([1, 4, 9, 12, 15])

array([ 9, 15,  1, 12,  4])

In [11]:
arr = np.arange(9).reshape((3, 3))
np.random.permutation(arr)

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

In [12]:
#元のデータはシャッフルしたくない時はpermutationを使ってindexをシャッフルする
A = np.arange(100)
x = np.random.permutation(100)
A[x]

array([48, 64,  2, 60, 81, 13,  9, 92,  0, 51,  6, 49, 41, 33, 77, 21, 95,
       57, 82, 36, 10, 91, 18, 84,  3, 28, 40,  1, 87, 80, 38, 53, 42, 27,
       72,  5, 23, 97, 46, 58, 70, 24, 15, 85, 17, 83, 69, 86, 26, 16, 73,
       34, 12, 45, 56, 74, 76,  7, 96, 94, 19, 11, 63, 65, 79, 43, 59, 50,
       22,  4, 98, 14, 37, 62, 47, 78,  8, 31, 89, 44, 32, 71, 30, 90, 66,
       93, 35, 55, 75, 25, 68, 61, 88, 39, 99, 29, 67, 52, 54, 20])

In [13]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])