In [2]:
import numpy as np

## Normal distribution

In [3]:
#normal([loc, scale, size])  Draw random samples from a normal (Gaussian) distribution.
#  loc:Mean of the distribution
#  scale:Standard deviation of the destribution
#  size:Output shape
np.random.normal(0,1,10)

array([ 0.01367476, -0.25420173,  0.51786405, -0.61409872, -2.60389992,
        0.80180497, -0.78150386, -0.7453864 , -2.35625315,  0.46878384])

## Uniform distribution

In [4]:
#uniform([low, high, size])  Draw samples from a uniform distribution.
#  low:Lower boundary of the output interval
#  high:Upper boundary of the output interva
#  size:Output shape
np.random.uniform(-1,1,10)

array([-0.89881461, -0.44836906, -0.28614713,  0.21968738,  0.9199067 ,
       -0.50418867, -0.58616121,  0.04713009,  0.18971406,  0.95137969])

## Shuffling

In [20]:
#shuffle(x)  Modify a sequence in-place by shuffling its contents.
#  x:The array or list to be shuffled.
arr=[i+1 for i in range(10)]
print(arr)
np.random.shuffle(arr) #shuffled in place
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


[3, 2, 6, 9, 4, 10, 7, 1, 5, 8]

## Permutation

In [21]:
#permutation(x)  Randomly permute a sequence, or return a permuted range.
#  x:The array or list to be shuffled.
arr=[i+1 for i in range(10)]
print(arr)
np.random.permutation(arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


array([ 3,  6,  5, 10,  2,  8,  4,  9,  1,  7])