In [4]:
import numpy as np
s = np.random.standard_normal(8000)

In [5]:
s

array([ 1.06878097,  0.79838837, -0.80895381, ...,  0.45737831,
        0.21149411, -0.25217402])

In [6]:
l = np.random.uniform(-1,0,1000)

In [7]:
l

array([-2.46640848e-02, -8.82436295e-01, -1.46491311e-01, -8.75299211e-01,
       -1.61025854e-01, -5.32852828e-01, -9.44506055e-02, -3.60491577e-01,
       -3.06050256e-01, -6.92347719e-01, -8.27640523e-01, -9.87400818e-01,
       -5.56826993e-01, -9.99973845e-01, -7.96095117e-01, -8.85584145e-02,
       -2.03600085e-01, -3.29989352e-01, -3.61409481e-01, -6.44853152e-01,
       -6.42826400e-01, -2.19310982e-01, -8.31031456e-01, -5.30074134e-01,
       -4.82921584e-01, -9.13683680e-01, -7.75047958e-01, -3.63499394e-01,
       -8.32111725e-01, -3.02404688e-01, -6.55665393e-01, -2.55390600e-01,
       -9.99582917e-01, -3.76790629e-01, -4.76829582e-01, -1.98951837e-01,
       -8.98139534e-01, -6.99132714e-01, -3.29750065e-01, -7.22121162e-01,
       -7.58893923e-02, -9.94089782e-02, -1.11437991e-01, -6.85702174e-01,
       -1.09673810e-01, -3.94626972e-02, -3.19070294e-03, -7.52735453e-01,
       -5.14967337e-01, -1.04694869e-01, -1.06759879e-01, -3.13283793e-01,
       -3.99511937e-01, -

In [8]:
arr = np.arange(50)

In [9]:
np.random.shuffle(arr)

In [10]:
arr

array([ 3,  5, 20, 16, 21, 14, 30, 12, 44, 41, 15, 29,  2, 36, 22, 34, 28,
       11, 19, 35, 37,  0, 42, 18, 33, 25, 13,  9,  7,  6, 31, 27, 24, 23,
       39, 45, 46, 26, 17, 10, 48, 43,  8, 38,  4, 32, 49, 47, 40,  1])

In [11]:
np.random.permutation(50)

array([ 1, 30,  5, 33,  2,  0, 45, 38, 29, 34, 48,  8,  3, 21, 23, 25, 41,
       24, 42, 28, 22, 47, 31, 35, 32, 17, 39, 27, 19,  4, 37, 15, 49,  7,
       46, 26, 12,  6, 13, 14, 40, 18, 43, 11,  9, 36, 10, 16, 20, 44])