In [46]:
from sklearn import tree
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

size and dim of X and Y

In [48]:
clf.predict([[2., 2.]]) # What does this line do?

array([1])

In [49]:
clf.predict([[2.,2.],[2.,3.]]) # What does this line do?

array([1, 1])

In [37]:
clf.predict_proba([[2., 2.]]) # What does this do?

array([[0., 1.],
       [1., 0.]])

In [ ]:
clf.predict_proba([[2., 2.],[0.,-1.]]) # What does this do?

In [39]:
from sklearn.datasets import load_iris
from sklearn import tree
iris = load_iris()
clf = tree.DecisionTreeClassifier()
clf = clf.fit(iris.data, iris.target)

In [40]:
iris.data.shape

(150, 4)

In [41]:
iris.target.size

150

In [42]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [43]:
clf.predict([[1,2,1,4],[2,2,1,1]])

array([0, 0])

In [44]:
clf.predict_proba([[1,2,1,4],[1,2,1,4]]) # How different is this from the previous case?

array([[1., 0., 0.],
       [1., 0., 0.]])

In [8]:
# pip install graphviz
# Download Graphviz executable on your PC https://graphviz.gitlab.io/download/
import graphviz 
dot_data = tree.export_graphviz(clf, out_file=None) 
graph = graphviz.Source(dot_data) 
graph.render("iris") 

ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'iris'], make sure the Graphviz executables are on your systems' PATH

Generate a data set to manipulate "decision tree classification".
Random value generation:
Go to https://www.numpy.org/devdocs/reference/generated/numpy.random.randn.html .

Make models that are good for decision tree classification.

In [53]:
import os
os.getcwd() 

'C:\\Users\\ryamada\\Desktop'

In [52]:
os.chdir("C:\\Users\\ryamada\\Desktop")