In [49]:
from sklearn import tree
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

In [50]:
import os
os.getcwd()

'C:\\Users\\ryamada\\Desktop\\gitclone\\JD_lectures\\StatLearnII'

size and dim of X and Y

In [51]:
clf.predict([[2., 2.]]) # What does this line do?

array([1])

In [52]:
clf.predict([[2.,2.],[2.,3.]]) # What does this line do?

array([1, 1])

In [53]:
clf.predict_proba([[2., 2.]]) # What does this do?

array([[0., 1.]])

In [54]:
clf.predict_proba([[2., 2.],[0.,-1.]]) # What does this do?

array([[0., 1.],
       [1., 0.]])

In [55]:
from sklearn.datasets import load_iris
from sklearn import tree
iris = load_iris()
clf = tree.DecisionTreeClassifier()
clf = clf.fit(iris.data, iris.target)

In [56]:
iris.data.shape

(150, 4)

In [57]:
iris.target.size

150

In [58]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [59]:
clf.predict([[1,2,1,4],[2,2,1,1]])

array([2, 1])

In [60]:
clf.predict_proba([[1,2,1,4],[1,2,1,4]]) # How different is this from the previous case?

array([[0., 0., 1.],
       [0., 0., 1.]])

In [64]:
# pip install graphviz
# conda install graphviz
## Graphviz will be installed into 'C:\Users\ryamada\Anaconda3\Library\bin\graphviz''
# Or download Graphviz executable on your PC https://graphviz.gitlab.io/download/
## In this case Graphviz will be installed into 'C:\Program Files (x86)\Graphviz2.38\bin'
import graphviz 
dot_data = tree.export_graphviz(clf, out_file=None) 


In [62]:
graph = graphviz.Source(dot_data) 
# This command generate a file "iris", that is in the Graphviz format.
# You can visualize this "iris" with GVEdit, a GUI Graphviz application,
# and you can save its graph-picture.

In [63]:
graph.render("iris") 
# Windows 7: No success even after hours on PATH issue.
# may "dot -Kdot -Tpng irsi -o iris.png" @ your terminal

ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'iris'], make sure the Graphviz executables are on your systems' PATH

Generate a data set to manipulate "decision tree classification".
Random value generation:
Go to https://www.numpy.org/devdocs/reference/generated/numpy.random.randn.html .

Make models that are good for decision tree classification.

In [53]:
import os
os.getcwd() 

'C:\\Users\\ryamada\\Desktop'

In [52]:
os.chdir("C:\\Users\\ryamada\\Desktop")