# Report the various methods of distance measure, implemented in dist() function of R or distance() function of R, which implements more than dist()

Rのdist()関数の距離は  
・ユークリッド距離（euclidean）：最も一般的。二次元ならピタゴラスの定理。L2距離。  
・バイナリ距離（binary）：0,1データの距離。  
・マンハッタン距離（manhattan）：座標の差の総和。L1距離。  
・ミンコフスキー距離（minkowski）：一般化した距離。  
・キャンベラ距離（canberra）：マンハッタン距離の亜型？原点近くでは重みがつく。  
・最長距離（maximum）：要素同士の差の絶対値が最大のもの。  
の6種類が指定できる。  
一方、distance()では46種類の距離から選択できる。

#デフォルトはユークリッド距離

In [1]:
require(graphics)

x <- matrix(rnorm(100), nrow = 5)
x

[,1]        [,2]       [,3]       [,4]        [,5]        [,6]        
[1,]  0.33689183 -1.6828727 -0.5179126  0.87193775 -0.17753557  0.007309874
[2,] -0.07504415 -0.1683685 -0.3642543  1.63087919 -0.29762414  1.107199413
[3,] -0.37465180  0.8806566 -0.7115029 -0.11521214 -0.15652291  0.585604566
[4,]  0.45488265  0.8503924 -0.2626034  0.11674605 -0.02959316 -1.394547959
[5,]  1.02617486  0.7923771 -0.6272234 -0.02089143  0.29346401  1.201306104
     [,7]       [,8]       [,9]       [,10]       [,11]        [,12]      
[1,] -0.6205077  0.5345761  0.4216474  0.94816084 -0.006652332 -0.42011748
[2,] -0.2211886 -1.1114820 -0.1786264  0.03104579  0.788192649  1.66466404
[3,] -1.3562655 -0.2446762  0.1987854 -1.47143965  2.026967295 -0.10147671
[4,]  0.7798089  0.6505648  0.4020653  1.51877573  0.356461607 -0.11566367
[5,] -1.4662149  0.1047870 -0.7518843  0.40765446 -0.071083228 -0.06989938
     [,13]       [,14]      [,15]       [,16]      [,17]      [,18]     
[1,] -0.84287871  0.7618359 -0.82349304 -0.4139681  1.1468718  1.4489551
[2,] -0.14671725 -1.1078630 -0.09351244 -0.8387908  1.0323221  0.3264371
[3,]  0.28131966  0.3137338 -0.61951058 -1.2330865 -0.7781282  0.3095638
[4,] -1.08034460 -1.9670799 -0.14205699  0.9086219  0.2039386 -0.0312407
[5,] -0.08142902 -1.2723285  1.89221316  0.4514981 -1.1343853  0.1352010
     [,19]      [,20]    
[1,] -1.4975659 -1.108580
[2,]  0.1252805 -1.129146
[3,]  1.6483441  1.014974
[4,]  1.8597352  1.392355
[5,] -0.5761837 -1.085970

In [2]:
dist(x)

         1        2        3        4
2 4.683659                           
3 6.426654 5.155227                  
4 6.473178 5.900143 5.929424         
5 5.689979 4.837639 5.731758 5.927931

In [3]:
dist(x, diag = TRUE)

         1        2        3        4        5
1 0.000000                                    
2 4.683659 0.000000                           
3 6.426654 5.155227 0.000000                  
4 6.473178 5.900143 5.929424 0.000000         
5 5.689979 4.837639 5.731758 5.927931 0.000000

In [4]:
dist(x, upper = TRUE)

         1        2        3        4        5
1          4.683659 6.426654 6.473178 5.689979
2 4.683659          5.155227 5.900143 4.837639
3 6.426654 5.155227          5.929424 5.731758
4 6.473178 5.900143 5.929424          5.927931
5 5.689979 4.837639 5.731758 5.927931         

In [5]:
m <- as.matrix(dist(x))
d <- as.dist(m)
m

1        2        3        4        5       
1 0.000000 4.683659 6.426654 6.473178 5.689979
2 4.683659 0.000000 5.155227 5.900143 4.837639
3 6.426654 5.155227 0.000000 5.929424 5.731758
4 6.473178 5.900143 5.929424 0.000000 5.927931
5 5.689979 4.837639 5.731758 5.927931 0.000000

In [6]:
d

         1        2        3        4
2 4.683659                           
3 6.426654 5.155227                  
4 6.473178 5.900143 5.929424         
5 5.689979 4.837639 5.731758 5.927931

＃バイナリ距離

In [7]:
x <- c(0, 0, 1, 1, 1, 1)
y <- c(1, 0, 1, 1, 0, 1)
dist(rbind(x, y), method = "binary")

    x
y 0.4

0と1は遠くて、0と0、1と1は近い → 2/5=0.4

＃キャンベラ距離

In [8]:
dist(rbind(x, y), method = "canberra")

    x
y 2.4

色々な距離

In [9]:
x[6] <- Inf
(m2 <- rbind(x, y))
dist(m2, method = "binary")   # warning, answer 0.5 = 2/4
## These all give "Inf":
stopifnot(Inf == dist(m2, method =  "euclidean"),
          Inf == dist(m2, method =  "maximum"),
          Inf == dist(m2, method =  "manhattan"))
##  "Inf" is same as very large number:
x1 <- x; x1[6] <- 1e100
stopifnot(dist(cbind(x, y), method = "canberra") ==
    print(dist(cbind(x1, y), method = "canberra")))

## 2)
y[6] <- Inf #-> 6-th pair is excluded
dist(rbind(x, y), method = "binary"  )   # warning; 0.5
dist(rbind(x, y), method = "canberra"  ) # 3
dist(rbind(x, y), method = "maximum")    # 1
dist(rbind(x, y), method = "manhattan")  # 2.4

[,1] [,2] [,3] [,4] [,5] [,6]
x 0    0    1    1    1    Inf 
y 1    0    1    1    0      1

Warning message in dist(m2, method = "binary"):
“treating non-finite values as NA”

    x
y 0.5

  1 2 3 4 5
2 2        
3 1 2      
4 1 2 0    
5 2 2 1 1  
6 1 2 1 1 2


Warning message in dist(rbind(x, y), method = "binary"):
“treating non-finite values as NA”

    x
y 0.5

  x
y 3

  x
y 1

    x
y 2.4

irisデータを使ってみる

In [10]:
data(iris)
dat<-iris[1:6,1:4]
dat

Sepal.Length Sepal.Width Petal.Length Petal.Width
1 5.1          3.5         1.4          0.2        
2 4.9          3.0         1.4          0.2        
3 4.7          3.2         1.3          0.2        
4 4.6          3.1         1.5          0.2        
5 5.0          3.6         1.4          0.2        
6 5.4          3.9         1.7          0.4

In [11]:
dist(dat)

          1         2         3         4         5
2 0.5385165                                        
3 0.5099020 0.3000000                              
4 0.6480741 0.3316625 0.2449490                    
5 0.1414214 0.6082763 0.5099020 0.6480741          
6 0.6164414 1.0908712 1.0862780 1.1661904 0.6164414

In [12]:
dist(dat,method="maximum")

    1   2   3   4   5
2 0.5                
3 0.4 0.2            
4 0.5 0.3 0.2        
5 0.1 0.6 0.4 0.5    
6 0.4 0.9 0.7 0.8 0.4

In [13]:
dist(dat,method="manhattan")

    1   2   3   4   5
2 0.7                
3 0.8 0.5            
4 1.0 0.5 0.4        
5 0.2 0.7 0.8 1.0    
6 1.2 1.9 2.0 2.0 1.2

In [14]:
dist(dat,method="canberra")

           1          2          3          4          5
2 0.09692308                                            
3 0.12262948 0.09012843                                 
4 0.14663521 0.08245515 0.09805428                      
5 0.02398550 0.10101010 0.12678840 0.15077629           
6 0.51273301 0.60908600 0.63456515 0.59011905 0.50856907

＃distanceを使ってみる

In [15]:
library(philentropy)

In [16]:
distance(dat)

Metric: 'euclidean' using unit: 'log'.


v1        v2        v3       v4        v5        v6       
v1 0.0000000 0.5385165 0.509902 0.6480741 0.1414214 0.6164414
v2 0.5385165 0.0000000 0.300000 0.3316625 0.6082763 1.0908712
v3 0.5099020 0.3000000 0.000000 0.2449490 0.5099020 1.0862780
v4 0.6480741 0.3316625 0.244949 0.0000000 0.6480741 1.1661904
v5 0.1414214 0.6082763 0.509902 0.6480741 0.0000000 0.6164414
v6 0.6164414 1.0908712 1.086278 1.1661904 0.6164414 0.0000000

In [17]:
distance(dat,method="manhattan")

Metric: 'manhattan' using unit: 'log'.


v1  v2  v3  v4  v5  v6 
v1 0.0 0.7 0.8 1.0 0.2 1.2
v2 0.7 0.0 0.5 0.5 0.7 1.9
v3 0.8 0.5 0.0 0.4 0.8 2.0
v4 1.0 0.5 0.4 0.0 1.0 2.0
v5 0.2 0.7 0.8 1.0 0.0 1.2
v6 1.2 1.9 2.0 2.0 1.2 0.0

distanceだと完全な距離行列として返ってくる

特別な例

In [18]:
CountMatrix <- rbind(1:10, 20:29, 30:39)
CountMatrix

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 20   21   22   23   24   25   26   27   28   29   
[3,] 30   31   32   33   34   35   36   37   38   39

In [19]:
## estimate probabilities from a count matrix
distance(CountMatrix, method = "euclidean", est.prob = "empirical")

Metric: 'euclidean' using unit: 'log'.


v1        v2         v3        
v1 0.0000000 0.12807130 0.13881717
v2 0.1280713 0.00000000 0.01074588
v3 0.1388172 0.01074588 0.00000000

In [20]:
## compute the euclidean distance for count data
## NOTE: some distance measures are only defined for probability values,
distance(CountMatrix, method = "euclidean")

Metric: 'euclidean' using unit: 'log'.


v1       v2       v3      
v1  0.00000 60.08328 91.70605
v2 60.08328  0.00000 31.62278
v3 91.70605 31.62278  0.00000

In [21]:
ProbMatrix <- rbind(1:10/sum(1:10), 20:29/sum(20:29),30:39/sum(30:39))
ProbMatrix
distance(ProbMatrix, method = "euclidean")

[,1]       [,2]       [,3]       [,4]       [,5]       [,6]      [,7]     
[1,] 0.01818182 0.03636364 0.05454545 0.07272727 0.09090909 0.1090909 0.1272727
[2,] 0.08163265 0.08571429 0.08979592 0.09387755 0.09795918 0.1020408 0.1061224
[3,] 0.08695652 0.08985507 0.09275362 0.09565217 0.09855072 0.1014493 0.1043478
     [,8]      [,9]      [,10]    
[1,] 0.1454545 0.1636364 0.1818182
[2,] 0.1102041 0.1142857 0.1183673
[3,] 0.1072464 0.1101449 0.1130435

Metric: 'euclidean' using unit: 'log'.


v1        v2         v3        
v1 0.0000000 0.12807130 0.13881717
v2 0.1280713 0.00000000 0.01074588
v3 0.1388172 0.01074588 0.00000000

In [22]:
## compute the Kullback-Leibler Divergence with different logarithm bases:
### case: unit = log (Default)
distance(ProbMatrix, method = "kullback-leibler", unit = "log")

### case: unit = log2 
distance(ProbMatrix, method = "kullback-leibler", unit = "log2")

### case: unit = log10 
distance(ProbMatrix, method = "kullback-leibler", unit = "log10")

Metric: 'kullback-leibler' using unit: 'log'.


v1         v2           v3          
v1 0.00000000 0.0965296706 0.1111323599
v2 0.09652967 0.0000000000 0.0005867893
v3 0.11113236 0.0005867893 0.0000000000

Metric: 'kullback-leibler' using unit: 'log2'.


v1        v2           v3          
v1 0.0000000 0.1392628771 0.1603301045
v2 0.1392629 0.0000000000 0.0008465581
v3 0.1603301 0.0008465581 0.0000000000

Metric: 'kullback-leibler' using unit: 'log10'.


v1         v2           v3          
v1 0.00000000 0.0419223033 0.0482641707
v2 0.04192230 0.0000000000 0.0002548394
v3 0.04826417 0.0002548394 0.0000000000