(1) Read LinearAlgebra4StatisticalGenetics_4(Least Squares with Matrix) before the class hour on May 15.

(2) Report R codes to generate positive-definite matrix, that is the matrix satisfying the features of covariance matrix, i.e., symmetric and all eigenvalues being positive with two ways; (i) by generating data matrix and making its covariance matirix, (ii) by generating a diagonal matrix whose diagonal elements >0 and sandwich it with rotation matrix and its inverse.


In [2]:
# (2)
# (i) by generating data matrix and making its covariance matirix
set.seed(1234)
nr <- 10
nc <- 2
M <- matrix(runif(nc*nr), nr, nc)
(Mc <- cov(M))

[,1]        [,2]       
[1,] 0.075560276 0.004230653
[2,] 0.004230653 0.074693291

In [3]:
eigen(Mc)

eigen() decomposition
$values
[1] 0.07937959 0.07087398

$vectors
           [,1]       [,2]
[1,] -0.7422705  0.6701004
[2,] -0.6701004 -0.7422705


In [29]:
# (2)
# (ii) by generating a diagonal matrix whose diagonal elements > 0
set.seed(1234)
nr <- 2
di <- sort(runif(nr, min=0, max=100))
print(di)
diagmat <- diag(di, nr)
diagmat

[1] 11.37034 62.22994


[,1]     [,2]    
[1,] 11.37034  0.00000
[2,]  0.00000 62.22994

In [30]:
# 回転行列を与える
(P <- matrix(runif(nr*nr), nr))
P <- sweep(P, 2, apply(P, 2, norm, type="2"), "/")
# 転置
(Pi <- solve(P))

[,1]      [,2]     
[1,] 0.6092747 0.8609154
[2,] 0.6233794 0.6403106

[,1]     [,2]     
[1,] -3.80850  5.120634
[2,]  4.56385 -4.460588

In [31]:
# 固有値分解の分解式
M <- P %*% diagmat %*% Pi

(ei <- eigen(M))

# 回転行列としてノルムが1 になるように
(Pn <- sweep(P, 2, apply(P, 2, norm, type="2"), "/"))

eigen() decomposition
$values
[1] 62.22994 11.37034

$vectors
          [,1]      [,2]
[1,] 0.8023986 0.6989699
[2,] 0.5967884 0.7151511


[,1]      [,2]     
[1,] 0.6989699 0.8023986
[2,] 0.7151511 0.5967884