# (i) by generating data matrix and making its covariance matirix

In [1]:
a <- c(1,2,3,4,5,6)
b <- c(2,4,6,8,2,9)
c <- c(3,9,5,6,10,8)
d <- c(10,20,30,40,50,55)
e <- c(7,10,9,4,6,20)

#データ行列を作成
M <- cbind(a,b,c,d,e)
M

#データ行列の共分散行列を作成
X <- cov(M)

#共分散行列の固有値が正となることを確認
eigen(X)

a b c  d  e 
[1,] 1 2  3 10  7
[2,] 2 4  9 20 10
[3,] 3 6  5 30  9
[4,] 4 8  6 40  4
[5,] 5 2 10 50  6
[6,] 6 9  8 55 20

eigen() decomposition
$values
[1] 317.82229908  27.95228246   7.29775419   2.39235030   0.00198064

$vectors
            [,1]        [,2]         [,3]        [,4]          [,5]
[1,] -0.10480002  0.01361067 -0.006744947  0.02800945  0.9939827377
[2,] -0.09069600  0.22074609 -0.746576701 -0.62102223 -0.0001514834
[3,] -0.08997085 -0.03725914  0.636315914 -0.76507086  0.0169010042
[4,] -0.97722583 -0.14971193 -0.014939144  0.10748591 -0.1041134668
[5,] -0.13313945  0.96295587  0.193537116  0.12907450 -0.0295471881


# (ii) by generating a diagonal matrix whose diagonal elements >0 and sandwich it with rotation matrix and its inverse.

In [2]:
#elements>0の対角行列Mを作成
M <- matrix(c(1,0,0,0,2,0,0,0,3), 3, 3)
M

#回転行列Rを作成
R <- matrix(c(cos(pi/3)%*%cos(pi/3)-sin(pi/3)%*%sin(pi/3)%*%sin(pi/3),-cos(pi/3)%*%sin(pi/3),sin(pi/3)%*%cos(pi/3)+sin(pi/3)%*%cos(pi/3)%*%sin(pi/3),cos(pi/3)%*%sin(pi/3)+sin(pi/3)%*%sin(pi/3)%*%cos(pi/3), cos(pi/3)%*%cos(pi/3), sin(pi/3)%*%sin(pi/3) - sin(pi/3)%*%cos(pi/3)%*%cos(pi/3),-cos(pi/3)%*%sin(pi/3), sin(pi/3), cos(pi/3)%*%cos(pi/3)),3,3)
R

#回転行列Rの逆行列を作成
R.inverse <- solve(R)
R.inverse

#MをRとR.inverseでsandwichした行列Xを作成
X <- R %*% M %*% R.inverse
X

#Xの固有値が正となることを確認
#Mの固有値と等しい（Mの対角成分が固有値となるので全て正）
eigen(X)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

[,1]       [,2]      [,3]      
[1,] -0.3995191 0.8080127 -0.4330127
[2,] -0.4330127 0.2500000  0.8660254
[3,]  0.8080127 0.5334936  0.2500000

[,1]       [,2]       [,3]     
[1,] -0.3995191 -0.4330127 0.8080127
[2,]  0.8080127  0.2500000 0.5334936
[3,] -0.4330127  0.8660254 0.2500000

[,1]       [,2]       [,3]     
[1,]  2.0278845 -0.5479968 0.2145633
[2,] -0.5479968  2.5625000 0.5663861
[3,]  0.2145633  0.5663861 1.4096155

eigen() decomposition
$values
[1] 3 2 1

$vectors
           [,1]      [,2]       [,3]
[1,]  0.4330127 0.8080127 -0.3995191
[2,] -0.8660254 0.2500000 -0.4330127
[3,] -0.2500000 0.5334936  0.8080127
