# Report R codes to generate positive-definite matrix, that is the matrix satisfying the features of covariance matrix, i.e., symmetric and all eigenvalues being positive with two ways; 

# (i) by generating data matrix and making its covariance matirix, 

# (ii) by generating a diagonal matrix whose diagonal elements >0 and sandwich it with rotation matrix and its inverse.

In [4]:
posi_def_mat1 <- function(k,n){
    data_mat <- matrix(rnorm(k*n), ncol=k)
    cov(data_mat)
}

In [5]:
M <- posi_def_mat1(2,100)
M
eigen(M)
M <- posi_def_mat1(3,100)
M
eigen(M)
M <- posi_def_mat1(5,100)
M
eigen(M)

[,1]       [,2]      
[1,] 0.81970995 0.04460562
[2,] 0.04460562 0.91106726

eigen() decomposition
$values
[1] 0.9292337 0.8015435

$vectors
          [,1]       [,2]
[1,] 0.3771868 -0.9261372
[2,] 0.9261372  0.3771868


[,1]        [,2]       [,3]       
[1,]  0.80500684 -0.1540392  0.02975865
[2,] -0.15403922  1.1258563 -0.04463770
[3,]  0.02975865 -0.0446377  1.10107652

eigen() decomposition
$values
[1] 1.212622 1.076632 0.742686

$vectors
           [,1]       [,2]        [,3]
[1,]  0.3467933  0.1318302  0.92863081
[2,] -0.8352315 -0.4070729  0.36970259
[3,]  0.4267584 -0.9038321 -0.03106144


[,1]        [,2]        [,3]        [,4]        [,5]       
[1,]  1.16903898 -0.19342196  0.34954546 -0.19841334 -0.03003484
[2,] -0.19342196  1.05163006 -0.12555377  0.09955105  0.07941408
[3,]  0.34954546 -0.12555377  1.07458290 -0.01709694 -0.04901374
[4,] -0.19841334  0.09955105 -0.01709694  0.95203281 -0.15874100
[5,] -0.03003484  0.07941408 -0.04901374 -0.15874100  1.11857798

eigen() decomposition
$values
[1] 1.6311819 1.2269858 0.9800838 0.8371368 0.6904744

$vectors
            [,1]        [,2]       [,3]       [,4]        [,5]
[1,]  0.69064535 -0.07700008 -0.1677795  0.3553741 -0.60219539
[2,] -0.40155202 -0.11287285 -0.7574221  0.4988104  0.05929205
[3,]  0.53876923  0.13328850 -0.5226038 -0.3909749  0.51573813
[4,] -0.25673848  0.49559888 -0.3189810 -0.5110731 -0.57054582
[5,] -0.07468628 -0.84731732 -0.1526373 -0.4591736 -0.20575913


In [2]:
library(GPArotation)
posi_def_mat2 <- function(n){
    val <- matrix(rnorm(n))
    eig <- val * val
    diag <- matrix(0,n,n)
    for(i in 1:n){
        diag[i,i] <- eig[i]
    }
    ortho <- Random.Start(n)
    M <- ortho %*% diag %*% t(ortho)
    M
}

In [3]:
M <- posi_def_mat2(2)
M
eigen(M)
M <- posi_def_mat2(3)
M
eigen(M)
M <- posi_def_mat2(5)
M
eigen(M)

[,1]        [,2]        
[1,]  1.27316302 -0.047041373
[2,] -0.04704137  0.001738106

eigen() decomposition
$values
[1] 1.274901e+00 9.901104e-10

$vectors
            [,1]        [,2]
[1,] -0.99931810 -0.03692323
[2,]  0.03692323 -0.99931810


[,1]       [,2]       [,3]      
[1,]  1.9675207  0.1436028 -0.2977541
[2,]  0.1436028  0.5838783 -0.2378904
[3,] -0.2977541 -0.2378904  0.2128719

eigen() decomposition
$values
[1] 2.03940938 0.65157201 0.07328947

$vectors
           [,1]       [,2]      [,3]
[1,]  0.9765142 -0.1830599 0.1136186
[2,]  0.1250216  0.9109324 0.3931562
[3,] -0.1754700 -0.3697178 0.9124248


[,1]       [,2]        [,3]       [,4]        [,5]       
[1,] 0.10845743  0.02784694  0.1190293  0.03241114  0.01096882
[2,] 0.02784694  0.22675232 -0.3696057 -0.32426709  0.01912933
[3,] 0.11902929 -0.36960573  0.9088064  0.66152948 -0.01590700
[4,] 0.03241114 -0.32426709  0.6615295  0.53880067 -0.02579338
[5,] 0.01096882  0.01912933 -0.0159070 -0.02579338  0.01211869

eigen() decomposition
$values
[1] 1.594696869 0.172489680 0.014863353 0.007340660 0.005544986

$vectors
            [,1]       [,2]       [,3]       [,4]       [,5]
[1,] -0.06569413  0.7528076 -0.3563117  0.3807255 -0.3963017
[2,]  0.33588484  0.4981513 -0.1666652 -0.3613328  0.6933166
[3,] -0.74489294  0.3417918  0.4321070 -0.3755624  0.0234357
[4,] -0.57234883 -0.2348012 -0.5997807  0.2586746  0.4366185
[5,]  0.02042015  0.1147723  0.5466364  0.7186981  0.4136085
